//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    public partial class BOOKING
    {
        [Key]
        public int BOOKING_ID { get; set; }

        [Required]
        [ForeignKey("TICKET_ID")]
        public int TICKET_ID { get; set; }

        [Required]
        [ForeignKey("CUSTOMER_ID")]
        public int CUSTOMER_ID { get; set; }

        [Required]
        public short BOOKING_QUANTITY { get; set; }

        [Required]
        public DateTime BOOKING_DATE_TIME { get; set; }

        [Required]
        public bool BOOKING_CANCELED { get; set; }
    }
}
