//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class CUSTOMER
    {
        [Required]
        [Key]
        public int CUSTOMER_ID { get; set; }

        [Required]
        public string CUSTOMER_FIRST_NAME { get; set; }

        [Required]
        public string CUSTOMER_LAST_NAME { get; set; }

        [Required]
        public string CUSTOMER_EMAIL { get; set; }

        [Required]
        public string CUSTOMER_ADDRESS { get; set; }

        [Required]
        public string CUSTOMER_POSTCODE { get; set; }

        [Required]
        public string CUSTOMER_PASSWORD { get; set; }
    }
}
