//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    public partial class GUEST_BOOKING
    {
        [Required]
        [Key]
        public int GUEST_BOOKING_ID { get; set; }

        [Required]
        [ForeignKey("TICKET_ID")]
        public int TICKET_ID { get; set; }

        [Required]
        public string GUEST_EMAIL { get; set; }

        [Required]
        public string GUEST_ADDRESS { get; set; }

        [Required]
        public string GUEST_POSTCODE { get; set; }

        [Required]
        public int GUEST_BOOKING_QUANTITY { get; set; }

        [Required]
        public DateTime GUEST_BOOKING_DATE_TIME { get; set; }
    }
}
