//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    public partial class LINEUP
    {
        [Required]
        [Key]
        public int LINEUP_ID { get; set; }

        [Required]
        [ForeignKey("ARTIST1_ID")]
        public int ARTIST1_ID { get; set; }

        [ForeignKey("ARTIST2_ID")]
        public Nullable<int> ARTIST2_ID { get; set; }

        [ForeignKey("ARTIST3_ID")]
        public Nullable<int> ARTIST3_ID { get; set; }

        [ForeignKey("ARTIST4_ID")]
        public Nullable<int> ARTIST4_ID { get; set; }

        [ForeignKey("ARTIST5_ID")]
        public Nullable<int> ARTIST5_ID { get; set; }

        [ForeignKey("ARTIST6_ID")]
        public Nullable<int> ARTIST6_ID { get; set; }

        [ForeignKey("ARTIST7_ID")]
        public Nullable<int> ARTIST7_ID { get; set; }

        [ForeignKey("ARTIST8_ID")]
        public Nullable<int> ARTIST8_ID { get; set; }

        [ForeignKey("ARTIST9_ID")]
        public Nullable<int> ARTIST9_ID { get; set; }

        [ForeignKey("ARTIST10_ID")]
        public Nullable<int> ARTIST10_ID { get; set; }
    }
}
