//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    public partial class PARENT_EVENT
    {
        [Required]
        [Key]
        public int PARENT_EVENT_ID { get; set; }

        [Required]
        [ForeignKey("SOCIAL_MEDIA_ID")]
        public int SOCIAL_MEDIA_ID { get; set; }

        [Required]
        public string PARENT_EVENT_NAME { get; set; }

        [Required]
        public string PARENT_EVENT_DESCRIPTION { get; set; }
    }
}
