//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class SOCIAL_MEDIA
    {
        [Required]
        [Key]
        public int SOCIAL_MEDIA_ID { get; set; }
        public byte[] IMAGE { get; set; }
        public string FACEBOOK { get; set; }
        public string TWITTER { get; set; }
        public string INSTAGRAM { get; set; }
        public string SOUNDCLOUD { get; set; }
        public string WEBSITE { get; set; }
        public string SPOTIFY { get; set; }
    }
}
