//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    public partial class TICKET
    {
        [Required]
        [Key]
        public int TICKET_ID { get; set; }

        [Required]
        [ForeignKey("CHILD_EVENT_ID")]
        public decimal CHILD_EVENT_ID { get; set; }

        [Required]
        public short TICKET_PRICE { get; set; }

        [Required]
        public string TICKET_DESCRIPTION { get; set; }

        [Required]
        public string TICKET_TOTAL_AMOUNT { get; set; }
    }
}
