//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    public partial class VENUE
    {
        [Required]
        [Key]
        public int VENUE_ID { get; set; }

        [Required]
        [ForeignKey("SOCIAL_MEDIA_ID")]
        public int SOCIAL_MEDIA_ID { get; set; }

        [Required]
        public string VENUE_DESCRIPTION { get; set; }

        [Required]
        public short VENUE_CAPACITY_SEATING { get; set; }

        [Required]
        public short VENUE_CAPACITY_STANDING { get; set; }

        [Required]
        public bool VENUE_DISABLED_ACCESS { get; set; }

        [Required]
        public string VENUE_FACILITES { get; set; }

        [Required]
        public int VENUE_PARKING { get; set; }
        
        public string VENUE_PHONE_NUMBER { get; set; }
        public string VENUE_EMAIL { get; set; }

        [Required]
        public string VENUE_ADDRESS { get; set; }

        [Required]
        public string VENUE_POSTCODE { get; set; }

        [Required]
        public string VENUE_NAME { get; set; }
    }
}
